/**
 * WeatherRenderer.js
 * ----------------------------------------------------------------------------
 * Overworld weather: wind, rain, snow and drifting mist (Phase 13).
 *
 * A MAP declares its weather — nothing here knows which maps are windy:
 *
 *   weather: { kind: 'wind', amount: 2 }     kind: wind | rain | snow | mist
 *                                            amount: 1 (light) to 3 (heavy)
 *
 * The story can change a sky. A map may list choices instead, and the FIRST
 * whose `when` holds is the one drawn (a choice with no `when` always holds,
 * so it goes last):
 *
 *   weather: [
 *     { when: 'stormriseRelayStopped', kind: 'wind', amount: 2 },
 *     { kind: 'mist', amount: 1 },
 *   ]
 *
 * Weather is a PICTURE only. It never blocks a tile, never changes a battle
 * and saves nothing; the map data and the world conditions alone decide it,
 * so a reload brings back exactly the same sky.
 *
 * PERFORMANCE
 * Every particle is made once, when the map loads, and recycled: one that
 * leaves the screen re-enters on the far side. Nothing is created or
 * destroyed per frame, so a storm costs a fixed number of small sprites —
 * at most a few dozen — however long the player stands in it.
 *
 * The plan for each kind (how many particles, how they move) is plain data in
 * `planWeather()`, so it is unit tested without Phaser.
 */

import { GAME_WIDTH, GAME_HEIGHT, DEPTHS } from '../config/gameConfig.js';
import { createSeededRandom } from '../utils/rng.js';

/**
 * What each kind of weather is made of. Per `amount` step:
 *   count     particles
 *   texture   generated by TextureFactory
 *   vx, vy    [min, max] speed in pixels per second
 *   alpha     [min, max]
 *   sway      sideways wobble in pixels (snow)
 */
export const WEATHER_KINDS = {
  wind: { count: 10, texture: 'fx-streak', vx: [260, 380], vy: [16, 40], alpha: [0.25, 0.55] },
  rain: { count: 18, texture: 'fx-drop', vx: [-70, -40], vy: [420, 540], alpha: [0.35, 0.6] },
  snow: { count: 14, texture: 'fx-flake', vx: [18, 48], vy: [36, 70], alpha: [0.6, 0.95], sway: 8 },
  mist: { count: 2, texture: 'fx-mist', vx: [10, 22], vy: [0, 4], alpha: [0.14, 0.26] },
};

/** The most particles any weather may use — a hard ceiling, tested. */
export const MAX_WEATHER_PARTICLES = 60;

/**
 * Turn a map's `weather` into a plan: which particles, how many, how fast.
 *
 * @param {{ kind: string, amount?: number } | undefined} weather
 * @returns {{ kind: string, count: number, texture: string, vx: number[],
 *             vy: number[], alpha: number[], sway: number } | null}
 */
export function planWeather(weather) {
  if (!weather || !Object.hasOwn(WEATHER_KINDS, weather.kind)) return null;
  const spec = WEATHER_KINDS[weather.kind];
  const amount = Math.min(3, Math.max(1, Math.round(weather.amount ?? 1)));
  return {
    kind: weather.kind,
    count: Math.min(MAX_WEATHER_PARTICLES, spec.count * amount),
    texture: spec.texture,
    vx: spec.vx,
    vy: spec.vy,
    alpha: spec.alpha,
    sway: spec.sway || 0,
  };
}

/**
 * Which sky a map shows right now: its one `weather`, or the first of its
 * choices whose `when` holds. Null for a map with none (or none that holds).
 *
 * @param {object | object[] | undefined} weather a map's `weather` field
 * @param {Record<string, boolean>} [conditions] world conditions
 * @returns {{ kind: string, amount?: number } | null}
 */
export function chooseWeather(weather, conditions = {}) {
  if (!weather) return null;
  if (!Array.isArray(weather)) return weather;
  return weather.find((choice) => !choice.when || conditions[choice.when]) || null;
}

/** List everything wrong with a map's `weather` field (empty when sound). */
export function findWeatherProblems(definition) {
  const weather = definition.weather;
  if (weather === undefined) return [];
  const where = `${definition.id} weather`;
  const problems = [];
  if (definition.interior) problems.push(`${where}: it does not rain indoors`);
  if (Array.isArray(weather)) {
    if (weather.length === 0) problems.push(`${where}: an empty list of choices`);
    weather.forEach((choice, index) => {
      problems.push(...findChoiceProblems(choice, `${where} choice ${index}`));
      // A choice with no `when` always holds, so anything after it is unreachable.
      if (choice && !choice.when && index < weather.length - 1) {
        problems.push(`${where} choice ${index}: has no "when", so the choices after it never show`);
      }
      if (choice && choice.when !== undefined && (typeof choice.when !== 'string' || !choice.when)) {
        problems.push(`${where} choice ${index}: "when" must name a condition`);
      }
    });
    return problems;
  }
  return [...problems, ...findChoiceProblems(weather, where)];
}

function findChoiceProblems(weather, where) {
  if (!weather || typeof weather !== 'object') return [`${where}: must be { kind, amount }`];
  const problems = [];
  if (!Object.hasOwn(WEATHER_KINDS, weather.kind)) {
    problems.push(`${where}: unknown kind "${weather.kind}" (try ${Object.keys(WEATHER_KINDS).join(', ')})`);
  }
  if (weather.amount !== undefined && (!Number.isInteger(weather.amount) || weather.amount < 1 || weather.amount > 3)) {
    problems.push(`${where}: amount must be 1, 2 or 3`);
  }
  return problems;
}

const between = ([min, max], random) => min + (max - min) * random();

export class WeatherRenderer {
  /**
   * @param {Phaser.Scene} scene
   * @param {{ kind: string, amount?: number }} weather one sky — see chooseWeather()
   */
  constructor(scene, weather) {
    this.scene = scene;
    this.plan = planWeather(weather);
    /** Which sky this is, so the scene can tell when the story changed it. */
    this.key = this.plan ? `${this.plan.kind}:${this.plan.count}` : 'none';
    /** @type {Array<{ sprite: Phaser.GameObjects.Image, vx: number, vy: number, phase: number }>} */
    this.particles = [];
    if (!this.plan) return;

    // Seeded, so the same map always opens on the same sky.
    const random = createSeededRandom(this.plan.count * 7919 + this.plan.kind.length);
    for (let i = 0; i < this.plan.count; i += 1) {
      const sprite = scene.add
        .image(random() * GAME_WIDTH, random() * GAME_HEIGHT, this.plan.texture)
        .setScrollFactor(0)
        .setDepth(DEPTHS.weather)
        .setAlpha(between(this.plan.alpha, random));
      this.particles.push({
        sprite,
        vx: between(this.plan.vx, random),
        vy: between(this.plan.vy, random),
        phase: random() * Math.PI * 2,
      });
    }
  }

  /** Move every particle; wrap the ones that leave the screen. No allocation. */
  update(delta) {
    if (!this.plan) return;
    const seconds = Math.min(delta, 100) / 1000;
    const margin = 48;
    for (const p of this.particles) {
      const sprite = p.sprite;
      p.phase += seconds * 2;
      sprite.x += p.vx * seconds + (this.plan.sway ? Math.sin(p.phase) * this.plan.sway * seconds : 0);
      sprite.y += p.vy * seconds;
      if (sprite.x > GAME_WIDTH + margin) sprite.x -= GAME_WIDTH + margin * 2;
      if (sprite.x < -margin) sprite.x += GAME_WIDTH + margin * 2;
      if (sprite.y > GAME_HEIGHT + margin) sprite.y -= GAME_HEIGHT + margin * 2;
      if (sprite.y < -margin) sprite.y += GAME_HEIGHT + margin * 2;
    }
  }

  destroy() {
    for (const p of this.particles) p.sprite.destroy();
    this.particles = [];
    this.plan = null;
  }
}
